asigm_1_proj - Assigment2/asigm_1_app/urls.py
from django.conf.urls import url
from . import views

app_name = "asigm1"
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<person_id>[0-9]+)/$', views.detail, name='detail'),
]

asigm_1_proj - Assigment2/asigm_1_proj/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^asigm_1_app/', include('asigm_1_app.urls'))
]

asigm_1_proj - Assigment2/asigm_1_app/models.py
from django.db import models

# Create your models here.
class Person(models.Model):
    name = models.CharField(max_length=100)
    age = models.IntegerField(null=True)
    address = models.CharField(max_length=100)
    mobile_number = models.IntegerField(null=True)
    def __str__(self):
        return self.name

asigm_1_proj - Assigment2/asigm_1_app/views.py
from django.shortcuts import render
from django.http import Http404, HttpResponse
from .models import Person
from django.template import loader
# Create your views here.
def index(request):
    latest_Person_list = Person.objects.order_by('-id')[:5]
    template = loader.get_template('asigm_1_app/index.html')
    context = {
        'latest_Person_list': latest_Person_list,
    }
    return HttpResponse(template.render(context, request))

def detail(request, person_id):
    try:
        person = Person.objects.get(pk=person_id)
    except Person.DoesNotExist:
        raise Http404("Person does not exist")
    return render(request, 'asigm_1_app/detail.html', {'person': person})

asigm_1_proj - Assigment2/asigm_1_app/templates/asigm_1_app/detail.html
<h2>Name: {{ person.name }}</h2>
<ul>
    <li>Age: {{ person.age }}</li>
    <li>Address: {{ person.address }}</li>
    <li>Mobile_number: {{ person.mobile_number }}</li>
</ul>

asigm_1_proj - Assigment2/asigm_1_app/templates/asigm_1_app/index.html
{% if latest_Person_list %}
    <ul>
        {% for person in latest_Person_list %}
        <li>
            <a href="{% url 'asigm1:detail' person.id %}">
                {{ person.name }}
            </a>
        </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No person are available</p>
{% endif %}